/**
 * generated by Xtext 2.18.0.M3
 */
package uk.ac.kcl.inf.szschaler.turtles.turtles;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Int Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.szschaler.turtles.turtles.IntExpression#getVal <em>Val</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.szschaler.turtles.turtles.IntExpression#getVar <em>Var</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.szschaler.turtles.turtles.TurtlesPackage#getIntExpression()
 * @model
 * @generated
 */
public interface IntExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' attribute.
   * @see #setVal(int)
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.TurtlesPackage#getIntExpression_Val()
   * @model
   * @generated
   */
  int getVal();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.IntExpression#getVal <em>Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' attribute.
   * @see #getVal()
   * @generated
   */
  void setVal(int value);

  /**
   * Returns the value of the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' reference.
   * @see #setVar(VariableDeclaration)
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.TurtlesPackage#getIntExpression_Var()
   * @model
   * @generated
   */
  VariableDeclaration getVar();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.IntExpression#getVar <em>Var</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' reference.
   * @see #getVar()
   * @generated
   */
  void setVar(VariableDeclaration value);

} // IntExpression
