/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.szschaler.turtles.turtles;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Move Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.szschaler.turtles.turtles.MoveStatement#getCommand <em>Command</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.szschaler.turtles.turtles.MoveStatement#getSteps <em>Steps</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.szschaler.turtles.turtles.TurtlesPackage#getMoveStatement()
 * @model
 * @generated
 */
public interface MoveStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Command</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.inf.szschaler.turtles.turtles.MoveCommand}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Command</em>' attribute.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.MoveCommand
   * @see #setCommand(MoveCommand)
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.TurtlesPackage#getMoveStatement_Command()
   * @model
   * @generated
   */
  MoveCommand getCommand();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.MoveStatement#getCommand <em>Command</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Command</em>' attribute.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.MoveCommand
   * @see #getCommand()
   * @generated
   */
  void setCommand(MoveCommand value);

  /**
   * Returns the value of the '<em><b>Steps</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Steps</em>' containment reference.
   * @see #setSteps(Expression)
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.TurtlesPackage#getMoveStatement_Steps()
   * @model containment="true"
   * @generated
   */
  Expression getSteps();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.MoveStatement#getSteps <em>Steps</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Steps</em>' containment reference.
   * @see #getSteps()
   * @generated
   */
  void setSteps(Expression value);

} // MoveStatement
