/**
 * generated by Xtext 2.18.0.M3
 */
package uk.ac.kcl.inf.szschaler.turtles.turtles;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.szschaler.turtles.turtles.TurtlesFactory
 * @model kind="package"
 * @generated
 */
public interface TurtlesPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "turtles";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/kcl/inf/szschaler/turtles/Turtles";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "turtles";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TurtlesPackage eINSTANCE = uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtleProgramImpl <em>Turtle Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtleProgramImpl
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getTurtleProgram()
   * @generated
   */
  int TURTLE_PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURTLE_PROGRAM__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Turtle Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURTLE_PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.StatementImpl
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 1;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.MoveStatementImpl <em>Move Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.MoveStatementImpl
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getMoveStatement()
   * @generated
   */
  int MOVE_STATEMENT = 2;

  /**
   * The feature id for the '<em><b>Command</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_STATEMENT__COMMAND = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Steps</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_STATEMENT__STEPS = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Move Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurnStatementImpl <em>Turn Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurnStatementImpl
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getTurnStatement()
   * @generated
   */
  int TURN_STATEMENT = 3;

  /**
   * The feature id for the '<em><b>Command</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURN_STATEMENT__COMMAND = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Degrees</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURN_STATEMENT__DEGREES = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Turn Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURN_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.MoveCommand <em>Move Command</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.MoveCommand
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getMoveCommand()
   * @generated
   */
  int MOVE_COMMAND = 4;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.TurnCommand <em>Turn Command</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.TurnCommand
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getTurnCommand()
   * @generated
   */
  int TURN_COMMAND = 5;


  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.TurtleProgram <em>Turtle Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Turtle Program</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.TurtleProgram
   * @generated
   */
  EClass getTurtleProgram();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.TurtleProgram#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.TurtleProgram#getStatements()
   * @see #getTurtleProgram()
   * @generated
   */
  EReference getTurtleProgram_Statements();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.MoveStatement <em>Move Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Move Statement</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.MoveStatement
   * @generated
   */
  EClass getMoveStatement();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.MoveStatement#getCommand <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Command</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.MoveStatement#getCommand()
   * @see #getMoveStatement()
   * @generated
   */
  EAttribute getMoveStatement_Command();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.MoveStatement#getSteps <em>Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Steps</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.MoveStatement#getSteps()
   * @see #getMoveStatement()
   * @generated
   */
  EAttribute getMoveStatement_Steps();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.TurnStatement <em>Turn Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Turn Statement</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.TurnStatement
   * @generated
   */
  EClass getTurnStatement();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.TurnStatement#getCommand <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Command</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.TurnStatement#getCommand()
   * @see #getTurnStatement()
   * @generated
   */
  EAttribute getTurnStatement_Command();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.TurnStatement#getDegrees <em>Degrees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Degrees</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.TurnStatement#getDegrees()
   * @see #getTurnStatement()
   * @generated
   */
  EAttribute getTurnStatement_Degrees();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.MoveCommand <em>Move Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Move Command</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.MoveCommand
   * @generated
   */
  EEnum getMoveCommand();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.TurnCommand <em>Turn Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Turn Command</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.TurnCommand
   * @generated
   */
  EEnum getTurnCommand();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TurtlesFactory getTurtlesFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtleProgramImpl <em>Turtle Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtleProgramImpl
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getTurtleProgram()
     * @generated
     */
    EClass TURTLE_PROGRAM = eINSTANCE.getTurtleProgram();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TURTLE_PROGRAM__STATEMENTS = eINSTANCE.getTurtleProgram_Statements();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.StatementImpl
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.MoveStatementImpl <em>Move Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.MoveStatementImpl
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getMoveStatement()
     * @generated
     */
    EClass MOVE_STATEMENT = eINSTANCE.getMoveStatement();

    /**
     * The meta object literal for the '<em><b>Command</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE_STATEMENT__COMMAND = eINSTANCE.getMoveStatement_Command();

    /**
     * The meta object literal for the '<em><b>Steps</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE_STATEMENT__STEPS = eINSTANCE.getMoveStatement_Steps();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurnStatementImpl <em>Turn Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurnStatementImpl
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getTurnStatement()
     * @generated
     */
    EClass TURN_STATEMENT = eINSTANCE.getTurnStatement();

    /**
     * The meta object literal for the '<em><b>Command</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TURN_STATEMENT__COMMAND = eINSTANCE.getTurnStatement_Command();

    /**
     * The meta object literal for the '<em><b>Degrees</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TURN_STATEMENT__DEGREES = eINSTANCE.getTurnStatement_Degrees();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.MoveCommand <em>Move Command</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.MoveCommand
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getMoveCommand()
     * @generated
     */
    EEnum MOVE_COMMAND = eINSTANCE.getMoveCommand();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.TurnCommand <em>Turn Command</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.TurnCommand
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getTurnCommand()
     * @generated
     */
    EEnum TURN_COMMAND = eINSTANCE.getTurnCommand();

  }

} //TurtlesPackage
