/**
 * generated by Xtext 2.18.0.M3
 */
package uk.ac.kcl.inf.szschaler.turtles.turtles;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.szschaler.turtles.turtles.TurtlesFactory
 * @model kind="package"
 * @generated
 */
public interface TurtlesPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "turtles";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/kcl/inf/szschaler/turtles/Turtles";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "turtles";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TurtlesPackage eINSTANCE = uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtleProgramImpl <em>Turtle Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtleProgramImpl
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getTurtleProgram()
   * @generated
   */
  int TURTLE_PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURTLE_PROGRAM__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Turtle Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURTLE_PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.StatementImpl
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 1;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.VariableDeclarationImpl
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getVariableDeclaration()
   * @generated
   */
  int VARIABLE_DECLARATION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__VALUE = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Variable Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.LoopStatementImpl <em>Loop Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.LoopStatementImpl
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getLoopStatement()
   * @generated
   */
  int LOOP_STATEMENT = 3;

  /**
   * The feature id for the '<em><b>Count</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP_STATEMENT__COUNT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP_STATEMENT__STATEMENTS = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Loop Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.MoveStatementImpl <em>Move Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.MoveStatementImpl
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getMoveStatement()
   * @generated
   */
  int MOVE_STATEMENT = 4;

  /**
   * The feature id for the '<em><b>Command</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_STATEMENT__COMMAND = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Steps</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_STATEMENT__STEPS = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Move Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurnStatementImpl <em>Turn Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurnStatementImpl
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getTurnStatement()
   * @generated
   */
  int TURN_STATEMENT = 5;

  /**
   * The feature id for the '<em><b>Command</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURN_STATEMENT__COMMAND = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Degrees</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURN_STATEMENT__DEGREES = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Turn Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURN_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.IntExpressionImpl <em>Int Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.IntExpressionImpl
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getIntExpression()
   * @generated
   */
  int INT_EXPRESSION = 6;

  /**
   * The number of structural features of the '<em>Int Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.IntLiteralImpl <em>Int Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.IntLiteralImpl
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getIntLiteral()
   * @generated
   */
  int INT_LITERAL = 7;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL__VAL = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.IntVarExpressionImpl <em>Int Var Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.IntVarExpressionImpl
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getIntVarExpression()
   * @generated
   */
  int INT_VAR_EXPRESSION = 8;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VAR_EXPRESSION__VAR = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Var Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VAR_EXPRESSION_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.AdditionImpl <em>Addition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.AdditionImpl
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getAddition()
   * @generated
   */
  int ADDITION = 9;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__LEFT = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__OPERATOR = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__RIGHT = INT_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Addition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.MultiplicationImpl <em>Multiplication</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.MultiplicationImpl
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getMultiplication()
   * @generated
   */
  int MULTIPLICATION = 10;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__LEFT = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__OPERATOR = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__RIGHT = INT_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Multiplication</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.MoveCommand <em>Move Command</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.MoveCommand
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getMoveCommand()
   * @generated
   */
  int MOVE_COMMAND = 11;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.TurnCommand <em>Turn Command</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.TurnCommand
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getTurnCommand()
   * @generated
   */
  int TURN_COMMAND = 12;


  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.TurtleProgram <em>Turtle Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Turtle Program</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.TurtleProgram
   * @generated
   */
  EClass getTurtleProgram();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.TurtleProgram#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.TurtleProgram#getStatements()
   * @see #getTurtleProgram()
   * @generated
   */
  EReference getTurtleProgram_Statements();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.VariableDeclaration <em>Variable Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Declaration</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.VariableDeclaration
   * @generated
   */
  EClass getVariableDeclaration();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.VariableDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.VariableDeclaration#getName()
   * @see #getVariableDeclaration()
   * @generated
   */
  EAttribute getVariableDeclaration_Name();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.VariableDeclaration#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.VariableDeclaration#getValue()
   * @see #getVariableDeclaration()
   * @generated
   */
  EAttribute getVariableDeclaration_Value();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.LoopStatement <em>Loop Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Loop Statement</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.LoopStatement
   * @generated
   */
  EClass getLoopStatement();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.LoopStatement#getCount <em>Count</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Count</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.LoopStatement#getCount()
   * @see #getLoopStatement()
   * @generated
   */
  EReference getLoopStatement_Count();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.LoopStatement#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.LoopStatement#getStatements()
   * @see #getLoopStatement()
   * @generated
   */
  EReference getLoopStatement_Statements();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.MoveStatement <em>Move Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Move Statement</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.MoveStatement
   * @generated
   */
  EClass getMoveStatement();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.MoveStatement#getCommand <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Command</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.MoveStatement#getCommand()
   * @see #getMoveStatement()
   * @generated
   */
  EAttribute getMoveStatement_Command();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.MoveStatement#getSteps <em>Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Steps</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.MoveStatement#getSteps()
   * @see #getMoveStatement()
   * @generated
   */
  EReference getMoveStatement_Steps();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.TurnStatement <em>Turn Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Turn Statement</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.TurnStatement
   * @generated
   */
  EClass getTurnStatement();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.TurnStatement#getCommand <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Command</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.TurnStatement#getCommand()
   * @see #getTurnStatement()
   * @generated
   */
  EAttribute getTurnStatement_Command();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.TurnStatement#getDegrees <em>Degrees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Degrees</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.TurnStatement#getDegrees()
   * @see #getTurnStatement()
   * @generated
   */
  EAttribute getTurnStatement_Degrees();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.IntExpression <em>Int Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Expression</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.IntExpression
   * @generated
   */
  EClass getIntExpression();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.IntLiteral <em>Int Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Literal</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.IntLiteral
   * @generated
   */
  EClass getIntLiteral();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.IntLiteral#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.IntLiteral#getVal()
   * @see #getIntLiteral()
   * @generated
   */
  EAttribute getIntLiteral_Val();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.IntVarExpression <em>Int Var Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Var Expression</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.IntVarExpression
   * @generated
   */
  EClass getIntVarExpression();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.IntVarExpression#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.IntVarExpression#getVar()
   * @see #getIntVarExpression()
   * @generated
   */
  EReference getIntVarExpression_Var();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.Addition <em>Addition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Addition</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.Addition
   * @generated
   */
  EClass getAddition();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.Addition#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.Addition#getLeft()
   * @see #getAddition()
   * @generated
   */
  EReference getAddition_Left();

  /**
   * Returns the meta object for the attribute list '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.Addition#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Operator</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.Addition#getOperator()
   * @see #getAddition()
   * @generated
   */
  EAttribute getAddition_Operator();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.Addition#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.Addition#getRight()
   * @see #getAddition()
   * @generated
   */
  EReference getAddition_Right();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.Multiplication <em>Multiplication</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multiplication</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.Multiplication
   * @generated
   */
  EClass getMultiplication();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.Multiplication#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.Multiplication#getLeft()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Left();

  /**
   * Returns the meta object for the attribute list '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.Multiplication#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Operator</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.Multiplication#getOperator()
   * @see #getMultiplication()
   * @generated
   */
  EAttribute getMultiplication_Operator();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.Multiplication#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.Multiplication#getRight()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Right();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.MoveCommand <em>Move Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Move Command</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.MoveCommand
   * @generated
   */
  EEnum getMoveCommand();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.TurnCommand <em>Turn Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Turn Command</em>'.
   * @see uk.ac.kcl.inf.szschaler.turtles.turtles.TurnCommand
   * @generated
   */
  EEnum getTurnCommand();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TurtlesFactory getTurtlesFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtleProgramImpl <em>Turtle Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtleProgramImpl
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getTurtleProgram()
     * @generated
     */
    EClass TURTLE_PROGRAM = eINSTANCE.getTurtleProgram();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TURTLE_PROGRAM__STATEMENTS = eINSTANCE.getTurtleProgram_Statements();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.StatementImpl
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.VariableDeclarationImpl
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getVariableDeclaration()
     * @generated
     */
    EClass VARIABLE_DECLARATION = eINSTANCE.getVariableDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECLARATION__NAME = eINSTANCE.getVariableDeclaration_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECLARATION__VALUE = eINSTANCE.getVariableDeclaration_Value();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.LoopStatementImpl <em>Loop Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.LoopStatementImpl
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getLoopStatement()
     * @generated
     */
    EClass LOOP_STATEMENT = eINSTANCE.getLoopStatement();

    /**
     * The meta object literal for the '<em><b>Count</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOOP_STATEMENT__COUNT = eINSTANCE.getLoopStatement_Count();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOOP_STATEMENT__STATEMENTS = eINSTANCE.getLoopStatement_Statements();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.MoveStatementImpl <em>Move Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.MoveStatementImpl
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getMoveStatement()
     * @generated
     */
    EClass MOVE_STATEMENT = eINSTANCE.getMoveStatement();

    /**
     * The meta object literal for the '<em><b>Command</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE_STATEMENT__COMMAND = eINSTANCE.getMoveStatement_Command();

    /**
     * The meta object literal for the '<em><b>Steps</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MOVE_STATEMENT__STEPS = eINSTANCE.getMoveStatement_Steps();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurnStatementImpl <em>Turn Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurnStatementImpl
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getTurnStatement()
     * @generated
     */
    EClass TURN_STATEMENT = eINSTANCE.getTurnStatement();

    /**
     * The meta object literal for the '<em><b>Command</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TURN_STATEMENT__COMMAND = eINSTANCE.getTurnStatement_Command();

    /**
     * The meta object literal for the '<em><b>Degrees</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TURN_STATEMENT__DEGREES = eINSTANCE.getTurnStatement_Degrees();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.IntExpressionImpl <em>Int Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.IntExpressionImpl
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getIntExpression()
     * @generated
     */
    EClass INT_EXPRESSION = eINSTANCE.getIntExpression();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.IntLiteralImpl <em>Int Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.IntLiteralImpl
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getIntLiteral()
     * @generated
     */
    EClass INT_LITERAL = eINSTANCE.getIntLiteral();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_LITERAL__VAL = eINSTANCE.getIntLiteral_Val();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.IntVarExpressionImpl <em>Int Var Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.IntVarExpressionImpl
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getIntVarExpression()
     * @generated
     */
    EClass INT_VAR_EXPRESSION = eINSTANCE.getIntVarExpression();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INT_VAR_EXPRESSION__VAR = eINSTANCE.getIntVarExpression_Var();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.AdditionImpl <em>Addition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.AdditionImpl
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getAddition()
     * @generated
     */
    EClass ADDITION = eINSTANCE.getAddition();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION__LEFT = eINSTANCE.getAddition_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADDITION__OPERATOR = eINSTANCE.getAddition_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION__RIGHT = eINSTANCE.getAddition_Right();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.impl.MultiplicationImpl <em>Multiplication</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.MultiplicationImpl
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getMultiplication()
     * @generated
     */
    EClass MULTIPLICATION = eINSTANCE.getMultiplication();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__LEFT = eINSTANCE.getMultiplication_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MULTIPLICATION__OPERATOR = eINSTANCE.getMultiplication_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__RIGHT = eINSTANCE.getMultiplication_Right();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.MoveCommand <em>Move Command</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.MoveCommand
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getMoveCommand()
     * @generated
     */
    EEnum MOVE_COMMAND = eINSTANCE.getMoveCommand();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.szschaler.turtles.turtles.TurnCommand <em>Turn Command</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.TurnCommand
     * @see uk.ac.kcl.inf.szschaler.turtles.turtles.impl.TurtlesPackageImpl#getTurnCommand()
     * @generated
     */
    EEnum TURN_COMMAND = eINSTANCE.getTurnCommand();

  }

} //TurtlesPackage
