/*
 * generated by Xtext 2.18.0.M3
 */
package uk.ac.kcl.inf.szschaler.turtles.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import uk.ac.kcl.inf.szschaler.turtles.ui.internal.TurtlesActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TurtlesExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(TurtlesActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		TurtlesActivator activator = TurtlesActivator.getInstance();
		return activator != null ? activator.getInjector(TurtlesActivator.UK_AC_KCL_INF_SZSCHALER_TURTLES_TURTLES) : null;
	}

}
