/*
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.szschaler.turtles.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uk.ac.kcl.inf.szschaler.turtles.ui.internal.TurtlesActivator;

public class TurtlesUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TurtlesActivator.getInstance().getInjector("uk.ac.kcl.inf.szschaler.turtles.Turtles");
	}

}
